### ISSUE TITLE
Regarding callable list object

### ISSUE THREAD

**Issue by jeremyblow** [miniaturemoose96/Tic-Tac-Toe#1]
Sorry, need to re-edit, misread some of the stuff.

**Comment by jeremyblow** [comment]
Let's walk this through with "whys", starting with the Traceback:

```
Traceback (most recent call last):
  File "TicTacToeGame.py", line 158, in <module>
    main()
  File "TicTacToeGame.py", line 132, in main
    board_full = game.is_board_full(board)
  File "TicTacToeGame.py", line 78, in is_board_full
    if is_space_valid(self.empty_board, pos):
TypeError: 'list' object is not callable
```
**Observation**: The game generates `TypeError: 'list' object is not callable`.
**Why?**: On line 78, in the `is_board_full ` function, we attempted to call `is_space_valid`, however `is_space_valid` is a list and thus not callable.
**Why?**: Because lists don't define any specific behavior, instead they store information.

Fair enough. Let's take a step back and make a larger observation. 

**Observation**: `is_space_valid` on line 78 doesn't work as intended.
**Why?**: Because `is_space_valid` is a list instead of a function or method.
**Why?**: Because on line 132 we pass the `board` list as the argument to the `is_board_full` method, so that tries to get called instead of our `TicTacToeGame .is_space_valid` method. 
**Why?**: Because on line 78 we try to call the `board` list instead of the instance method `self.is_space_valid`. 
**Why?**: Because the `is_board_full` method signature expects for an `is_space_valid` function, but instead should be using the `is_space_valid` method on the `self` instance. (root cause)

Let's think about `is_board_full`:

```python
    def is_board_full(self, is_space_valid):
        # Checks if the board is full
        for pos in range(1, 10):
            if is_space_valid(self.empty_board, pos):
                return False
            else:
                return True
```

The stated goal is to "Checks if the board is full", presumably returning True if the game board is full, and False if not. This is reinforced by the method naming: `is_board_full`. Abstractly, we need to ask *what board* are we referring to? Which board should be checked? Your `TicTacToeGame` class has a container for `empty_board`, which would lead one to presume that that should always be empty. So, I don't believe that is not the game board we should be checking, but rather a different one. On line 105 I can see that you create a new `board = [" "]*10`, which is probably the game board we want to check. 

Given that `is_board_full` wants to check if a provided board is full, then we should pass this `board` instance to it. Well, this is exactly as you done on lines 116 and 132:

```python
                full_board = game.is_board_full(board
...
                board_full = game.is_board_full(board)
```

So far, so good, but things quickly unravel from here. We can see in the signature that the `board` definitely is not the same as `is_space_valid`. This is an indication that the interface needs to be thought through more fully. 

To creep closer to the likely intended interface, we might do:

```python
    def is_board_full(self, board):
        # Checks if the board is full
        for pos in range(1, 10):
            if self.is_space_valid(board, pos):
                return False
            else:
                return True
```

However, if we do that, it only highlights more clearly that the function is not actually doing what it advertises itself as doing. Here's where you need to take a big step back and decide what your interface should be. How would we check if a board is full? One approach might be:

```python
    def is_board_full(self, board):
        # Checks if the board is full
        return not any([pos == " " for pos in board])
```

`TicTacToeGame` would then have a method to check if any game board is full. But, I would expect there to be only one board for every game - thus this method doesn't map very well to real-world usage. What might be done instead is to add a data attribute for the board for an instance of a game, e.g. `self.board = [" ", " ", " ", " ", " ", " ", " ", " ", " ", " "]` in your __init__ method. Then, whenever needed to operate on the board for the game, you might do:

```python
    def is_board_full(self):
        # Checks if the board is full
        return not any([pos == " " for pos in self.board])
```

Giving you the ability to check if the board is full any time by either calling `self.is_board_full()` internally or `game.is_board_full()` externally. 

A hunch says that this might map better to real-world usage if you define a board class. The *code smell* is `is_board_full`, it might be more expressive to think interact with the interface with something that looks like `game.board.is_full()`. This would allow you to change the interface of the board without disturbing the interface of the game. This may incline you to really put things to do with the board in a `Board` class (positions, position state, full state, etc), and things to do with the game in a `Game` class (player names, winner, instance of the game board). 

Something to think about. 

Jeremy

**Comment by miniaturemoose96** [comment]
Hey Jeremy, 

I was able to remove the callable list error on Line 78, now the game is still not functioning properly and by that I mean my players function is not associating the right symbol to player 1 and player 2,

#def players(self):
        # Ask for the names of player 1 and player 2, then ask player 1 if they want to be O or X
        # When player 1 selects x or o random operator will decide first turn
        player = " "
        player_one = input("What is your name Player One >>> ")
        player_two = input("What is your name Player Two >>> ")
        print(f"Welcome {player_one} and {player_two}")
        os.system("cls")
        while player != self.symbol_X or player != self.symbol_O:
            player = input(f"{player_one} who do you want to be X or O? ").upper()
            if player == self.symbol_X:
                # Create a dictionary to represent the players x and o
                player_xo = {self.symbol_X: player_one, self.symbol_O: player_two}
                # Print who is X or O, Return the player dict for the next method
                return player_xo
            elif player == self.symbol_O:
                player_xo = {self.symbol_O: player_one, self.symbol_X: player_two}
                return player_xo
            else:
                print("Error please choose X or O...")

**Comment by miniaturemoose96** [comment]
Sorry I accidentally closed the issue did not mean to that...

Hey Jeremy,
I was able to remove the callable list error on Line 78, now the game is still not functioning properly and by that I mean my players function is not associating the right symbol to player 1 and player 2,

https://github.com/miniaturemoose96/Tic-Tac-Toe/blob/1740f705e2b1dcefd4f19599cee0f1a50289f775/TicTacToeGame.py#L25-L44

In this function I want to associate the player name with the symbol X or O, this association is done on `Line 37, player_xo = {self.symbol_X: player_one, self.symbol_O: player_two}` and `Line 41, player_xo = {self.symbol_O: player_one, self.symbol_X: player_two}` then I return the value the value of the dictionary. 
<B>Question: How can I get the value of the dictionary, in this case the name with out printing the whole dictionary?</B>

This is the result here I get the wrong player, I should get O but instead player X goes...

![image](https://user-images.githubusercontent.com/17755843/45257928-2cd39c80-b363-11e8-82e1-e6a3dcb70388.png)

Here is the random player function that uses random to select player turn. In this case I have already associated the players to their corresponding symbol, X or O, and I pass the dictionary `player_x0`. Once the random selection happens as in the picture above we get the wrong player to go first.
https://github.com/miniaturemoose96/Tic-Tac-Toe/blob/1740f705e2b1dcefd4f19599cee0f1a50289f775/TicTacToeGame.py#L62-L73

And finally the game does not allow the player to place their mark. I you were to input any number to try to move the game just comes to a halt and asks if you can play again.

![image](https://user-images.githubusercontent.com/17755843/45257937-62788580-b363-11e8-9ce8-0b3c6379eacf.png)

The most recently version of the code is in my second branch the `working-branch` for you to review it and see any errors I have missed in my functions.

Thank you again.
PS: sorry for the tardiness, hope everything is well and that you I having a great weekend! =)

Alejandro
